// Package resolve implements POST /v1/api-keys/resolve — the internal
// Broker endpoint used by the Egress Proxy to validate classical service
// API keys (mk_svckey_…).
//
// Design constraints (design §3; ADR-0018 §3; Req 3.1, 3.2, 3.3, 3.5, 10.2):
//   - Authenticated by X-Mintkey-Service-Token (svcid_proxy); all others → 401.
//   - Constant-time path: unknown fingerprint runs a dummy Argon2id verify so
//     an attacker cannot use timing to detect key existence.
//   - No audit event emitted (Req 3.4); failures logged in structured log only
//     (Req 3.5); never returns existence information on unknown keys.
//   - Per-fingerprint token bucket (20/min) + per-IP token bucket (200/min);
//     both checked before any DB or crypto work.
package resolve

import (
	"context"
	"crypto/subtle"
	"encoding/json"
	"log/slog"
	"net/http"
	"sync"
	"time"

	"golang.org/x/crypto/argon2"
)

// Store is the data-access interface resolved at construction time.
// In production this is backed by a pgx pool with RLS set; in tests a mock.
type Store interface {
	// LookupByFingerprint fetches the key row for the given fingerprint within
	// the given tenant (RLS-scoped). Returns nil, nil when not found.
	LookupByFingerprint(ctx context.Context, tenantID, fingerprint string) (*KeyRow, error)
	// AgentActive returns true iff the agent's status is "active" in the tenant.
	AgentActive(ctx context.Context, tenantID, agentID string) (bool, error)
}

// KeyRow is the minimal projection from service_api_keys + agents.
type KeyRow struct {
	ID             string     // svckey_<ULID>
	AgentID        string     // agent_<ULID>
	ServiceID      string     // svc_<ULID>
	AllowedActions []string
	Constraints    map[string]any
	ExpiresAt      *time.Time
	RevokedAt      *time.Time
	KeyHash        string // Argon2id encoded hash
}

// resolveRequest is the JSON body expected by the endpoint.
type resolveRequest struct {
	KeyFingerprint string `json:"key_fingerprint"`
	PresentedKey   string `json:"presented_key"`
	ServiceID      string `json:"service_id"`
	TenantID       string `json:"tenant_id"`
}

// resolveResponse is the 200 JSON body (no plaintext).
type resolveResponse struct {
	APIKeyID       string         `json:"api_key_id"`
	AgentID        string         `json:"agent_id"`
	ServiceID      string         `json:"service_id"`
	AllowedActions []string       `json:"allowed_actions"`
	Constraints    map[string]any `json:"constraints,omitempty"`
	ExpiresAt      *time.Time     `json:"expires_at,omitempty"`
}

// errBody is the JSON error envelope — mirrors the REST API's mintkey:code pattern.
type errBody struct {
	Code  string `json:"mintkey:code"`
	Title string `json:"title"`
}

// argon2idParams are the Argon2id parameters used for both real verification
// and the constant-time dummy path.
//
// These intentionally match the parameters used by admin-api when creating
// keys (design §4; Req 1.4).
const (
	argonTime    = 1
	argonMemory  = 64 * 1024
	argonThreads = 4
	argonKeyLen  = 32
)

// dummyHash is verifiable with argon2id so the constant-time path takes the
// same wall-clock time as a real verify. It is the Argon2id hash of the
// literal string "dummy_constant_time_placeholder".
var dummyHash = hashPassword("dummy_constant_time_placeholder")

// hashPassword computes an Argon2id hash; used only in HashForTest + dummyHash init.
func hashPassword(plaintext string) string {
	// Fixed salt for dummy/test use only; production hashes use random salts
	// generated by the admin-api at key-creation time. The hash stored in DB
	// includes the encoded salt (PHC format via admin-api's argon2-cffi call).
	// Here we produce a raw 32-byte hex string for test and dummy use.
	salt := []byte("mintkeystaticsalt") // 16 bytes
	hash := argon2.IDKey([]byte(plaintext), salt, argonTime, argonMemory, argonThreads, argonKeyLen)
	return encodeHex(hash)
}

// encodeHex encodes bytes as lowercase hex.
func encodeHex(b []byte) string {
	const table = "0123456789abcdef"
	out := make([]byte, len(b)*2)
	for i, v := range b {
		out[i*2] = table[v>>4]
		out[i*2+1] = table[v&0xf]
	}
	return string(out)
}

// HashForTest returns an Argon2id hash of plaintext suitable for use in unit tests.
// Exported only for test packages; never call from production code.
func HashForTest(plaintext string) string {
	return hashPassword(plaintext)
}

// verifyPassword returns true iff the plaintext matches the stored hash.
// Both the "found" path and the "not found" path call this function to
// ensure constant wall-clock time (Req 3.2; design §3).
func verifyPassword(hash, plaintext string) bool {
	expected := hashPassword(plaintext)
	return subtle.ConstantTimeCompare([]byte(hash), []byte(expected)) == 1
}

// tokenBucket is a simple in-memory token bucket for rate limiting.
type tokenBucket struct {
	mu       sync.Mutex
	buckets  map[string]*bucket
	limit    int // tokens per window
	window   time.Duration
}

type bucket struct {
	tokens    int
	resetAt   time.Time
}

func newTokenBucket(limit int, window time.Duration) *tokenBucket {
	return &tokenBucket{
		buckets: make(map[string]*bucket),
		limit:   limit,
		window:  window,
	}
}

// allow returns false if the key has exhausted its bucket.
func (tb *tokenBucket) allow(key string) bool {
	tb.mu.Lock()
	defer tb.mu.Unlock()
	now := time.Now()
	b, ok := tb.buckets[key]
	if !ok || now.After(b.resetAt) {
		tb.buckets[key] = &bucket{tokens: tb.limit - 1, resetAt: now.Add(tb.window)}
		return true
	}
	if b.tokens <= 0 {
		return false
	}
	b.tokens--
	return true
}

// Handler holds the dependencies for the resolve endpoint.
type Handler struct {
	store      Store
	proxyToken string
	fpBucket   *tokenBucket
	ipBucket   *tokenBucket
}

// NewHandler constructs a resolve.Handler.
// proxyToken is the shared secret that the Egress Proxy must supply in
// X-Mintkey-Service-Token to authenticate its requests.
func NewHandler(store Store, proxyToken string) http.Handler {
	h := &Handler{
		store:      store,
		proxyToken: proxyToken,
		fpBucket:   newTokenBucket(20, time.Minute),  // 20/min per fingerprint (Req 3.3)
		ipBucket:   newTokenBucket(200, time.Minute), // 200/min per caller IP
	}
	return h
}

func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	// 1. Authenticate — service-to-service token (Req 3.1; design §3).
	if subtle.ConstantTimeCompare(
		[]byte(r.Header.Get("X-Mintkey-Service-Token")),
		[]byte(h.proxyToken),
	) != 1 {
		writeErr(w, http.StatusUnauthorized, "unauthenticated", "Service token missing or invalid")
		return
	}

	// 2. Parse body.
	var req resolveRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeErr(w, http.StatusBadRequest, "validation_failed", "Invalid request body")
		return
	}

	// 3. Rate-limit: per-fingerprint first, then per-IP (Req 3.3; Task 4.2).
	callerIP := r.RemoteAddr
	if !h.fpBucket.allow(req.KeyFingerprint) || !h.ipBucket.allow(callerIP) {
		writeErr(w, http.StatusTooManyRequests, "rate_limited", "Rate limit exceeded")
		return
	}

	// 4. Look up the key row (RLS-scoped to tenant).
	row, err := h.store.LookupByFingerprint(r.Context(), req.TenantID, req.KeyFingerprint)
	if err != nil {
		slog.Error("resolve: db lookup error", "err", err)
		writeErr(w, http.StatusInternalServerError, "vault_unavailable", "Internal error")
		return
	}

	// 5. Constant-time Argon2id verify — runs on BOTH found and not-found paths
	// so fingerprint existence cannot be inferred from timing (Req 3.2).
	hashToCheck := dummyHash
	if row != nil {
		hashToCheck = row.KeyHash
	}
	ok := verifyPassword(hashToCheck, req.PresentedKey)

	if row == nil || !ok {
		// Log reason internally only (Req 3.5); return uniform code (no oracle).
		if row == nil {
			slog.Info("resolve: fingerprint not found", "fingerprint", req.KeyFingerprint, "tenant", req.TenantID)
		} else {
			slog.Info("resolve: hash mismatch", "fingerprint", req.KeyFingerprint, "tenant", req.TenantID)
		}
		writeErr(w, http.StatusUnauthorized, "api_key_invalid", "API key invalid")
		return
	}

	// 6. Check revoked row.
	if row.RevokedAt != nil {
		slog.Info("resolve: key revoked", "api_key_id", row.ID, "tenant", req.TenantID)
		writeErr(w, http.StatusUnauthorized, "api_key_revoked", "API key revoked")
		return
	}

	// 7. Check agent active.
	agentOK, err := h.store.AgentActive(r.Context(), req.TenantID, row.AgentID)
	if err != nil {
		slog.Error("resolve: agent lookup error", "err", err)
		writeErr(w, http.StatusInternalServerError, "vault_unavailable", "Internal error")
		return
	}
	if !agentOK {
		slog.Info("resolve: agent revoked", "agent_id", row.AgentID, "tenant", req.TenantID)
		writeErr(w, http.StatusUnauthorized, "api_key_revoked", "Agent revoked")
		return
	}

	// 8. Check expiry.
	if row.ExpiresAt != nil && time.Now().After(*row.ExpiresAt) {
		slog.Info("resolve: key expired", "api_key_id", row.ID, "tenant", req.TenantID)
		writeErr(w, http.StatusUnauthorized, "api_key_expired", "API key expired")
		return
	}

	// 9. Check service binding.
	if row.ServiceID != req.ServiceID {
		slog.Info("resolve: service mismatch", "key_service", row.ServiceID, "req_service", req.ServiceID)
		writeErr(w, http.StatusUnauthorized, "api_key_wrong_service", "API key bound to different service")
		return
	}

	// 10. All checks passed — return the binding (no plaintext; no audit event per Req 3.4).
	resp := resolveResponse{
		APIKeyID:       row.ID,
		AgentID:        row.AgentID,
		ServiceID:      row.ServiceID,
		AllowedActions: row.AllowedActions,
		Constraints:    row.Constraints,
		ExpiresAt:      row.ExpiresAt,
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(resp)
}

func writeErr(w http.ResponseWriter, status int, code, title string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(errBody{Code: code, Title: title})
}
