// vault.proto -- Mintkey Vault Adapter gRPC IDL.
//
// Stability tier: experimental.
// Version       : 0.1.0-preview.1.
//
// This service is the contract between every credential-aware Mintkey
// component and the Vault Adapter (container C6 in
// docs/01-architecture/02-container-view.md). The adapter is the only
// component that handles credential plaintext; consumers never persist
// plaintext returned by GetCredential and pass it only into per-request
// header injection (per ADR-0003).
//
// Per ADR-0008 (multi-tenancy), every operation is tenant-scoped; the
// adapter rejects requests whose tenant_id is empty or unknown.
//
// !! INTERNAL SERVICE !!
//   This gRPC service is NEVER exposed beyond the control plane's
//   trust boundary. It listens on a UDS or loopback gRPC endpoint with
//   mTLS in v1, with token-based authentication as a future option.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: vault.proto

package vaultv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VaultAdapter_GetCredential_FullMethodName           = "/mintkey.vault.v1.VaultAdapter/GetCredential"
	VaultAdapter_PutCredential_FullMethodName           = "/mintkey.vault.v1.VaultAdapter/PutCredential"
	VaultAdapter_RevokeCredential_FullMethodName        = "/mintkey.vault.v1.VaultAdapter/RevokeCredential"
	VaultAdapter_ListVersions_FullMethodName            = "/mintkey.vault.v1.VaultAdapter/ListVersions"
	VaultAdapter_ValidateServiceIdentity_FullMethodName = "/mintkey.vault.v1.VaultAdapter/ValidateServiceIdentity"
)

// VaultAdapterClient is the client API for VaultAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VaultAdapter is the credential storage interface. Backends are
// pluggable per ADR-0003 (file in v1; HashiCorp Vault in v2; SQL+KMS in
// v3); all backends expose this same interface.
type VaultAdapterClient interface {
	// GetCredential returns the plaintext credential value for one
	// (tenant_id, service_id, key_version) tuple. Used by the Egress
	// Proxy plugin (per ADR-0004) on every brokered request.
	//
	// Pass key_version = 0 to fetch the current credential version
	// (atomic relative to a credential.rotated event).
	//
	// Errors:
	//
	//	NOT_FOUND       — no credential exists for the tuple.
	//	PERMISSION_DENIED — caller lacks the read scope for the tenant.
	//	FAILED_PRECONDITION — credential is revoked.
	//	UNAVAILABLE     — backend (file/Vault/KMS) is unreachable.
	GetCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error)
	// PutCredential creates or rotates a credential. The adapter assigns
	// a new monotonic key_version per (tenant_id, service_id) and returns
	// it. The plaintext sent in the request lives in the adapter's memory
	// for the duration of the call, is sealed with a fresh DEK, and is
	// discarded; the cleartext value is NEVER persisted or logged.
	//
	// Errors:
	//
	//	INVALID_ARGUMENT — auth_scheme/value mismatch, missing required
	//	                   fields, or value too large.
	//	PERMISSION_DENIED — caller lacks the write scope.
	//	UNAVAILABLE      — backend cannot accept writes.
	PutCredential(ctx context.Context, in *PutCredentialRequest, opts ...grpc.CallOption) (*PutCredentialResponse, error)
	// RevokeCredential soft-deletes a non-current key_version. The adapter
	// refuses to revoke the current key_version (caller must rotate first).
	//
	// Errors:
	//
	//	FAILED_PRECONDITION — supplied key_version is the current one.
	//	NOT_FOUND           — no such version.
	RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*RevokeCredentialResponse, error)
	// ListVersions returns metadata-only descriptors for all key_versions
	// of one (tenant_id, service_id). Plaintext is NEVER included.
	// Used by the Admin REST API and AdminJS for operator inspection.
	ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error)
	// ValidateServiceIdentity validates a per-service boot secret per ADR-0014.2.
	// Used by Admin API, MCP Server, Broker, and the proxy plugin to authenticate to
	// the Vault Adapter on startup.
	ValidateServiceIdentity(ctx context.Context, in *ValidateServiceIdentityRequest, opts ...grpc.CallOption) (*ValidateServiceIdentityResponse, error)
}

type vaultAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewVaultAdapterClient(cc grpc.ClientConnInterface) VaultAdapterClient {
	return &vaultAdapterClient{cc}
}

func (c *vaultAdapterClient) GetCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialResponse)
	err := c.cc.Invoke(ctx, VaultAdapter_GetCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultAdapterClient) PutCredential(ctx context.Context, in *PutCredentialRequest, opts ...grpc.CallOption) (*PutCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutCredentialResponse)
	err := c.cc.Invoke(ctx, VaultAdapter_PutCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultAdapterClient) RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*RevokeCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCredentialResponse)
	err := c.cc.Invoke(ctx, VaultAdapter_RevokeCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultAdapterClient) ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVersionsResponse)
	err := c.cc.Invoke(ctx, VaultAdapter_ListVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultAdapterClient) ValidateServiceIdentity(ctx context.Context, in *ValidateServiceIdentityRequest, opts ...grpc.CallOption) (*ValidateServiceIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateServiceIdentityResponse)
	err := c.cc.Invoke(ctx, VaultAdapter_ValidateServiceIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultAdapterServer is the server API for VaultAdapter service.
// All implementations must embed UnimplementedVaultAdapterServer
// for forward compatibility.
//
// VaultAdapter is the credential storage interface. Backends are
// pluggable per ADR-0003 (file in v1; HashiCorp Vault in v2; SQL+KMS in
// v3); all backends expose this same interface.
type VaultAdapterServer interface {
	// GetCredential returns the plaintext credential value for one
	// (tenant_id, service_id, key_version) tuple. Used by the Egress
	// Proxy plugin (per ADR-0004) on every brokered request.
	//
	// Pass key_version = 0 to fetch the current credential version
	// (atomic relative to a credential.rotated event).
	//
	// Errors:
	//
	//	NOT_FOUND       — no credential exists for the tuple.
	//	PERMISSION_DENIED — caller lacks the read scope for the tenant.
	//	FAILED_PRECONDITION — credential is revoked.
	//	UNAVAILABLE     — backend (file/Vault/KMS) is unreachable.
	GetCredential(context.Context, *GetCredentialRequest) (*GetCredentialResponse, error)
	// PutCredential creates or rotates a credential. The adapter assigns
	// a new monotonic key_version per (tenant_id, service_id) and returns
	// it. The plaintext sent in the request lives in the adapter's memory
	// for the duration of the call, is sealed with a fresh DEK, and is
	// discarded; the cleartext value is NEVER persisted or logged.
	//
	// Errors:
	//
	//	INVALID_ARGUMENT — auth_scheme/value mismatch, missing required
	//	                   fields, or value too large.
	//	PERMISSION_DENIED — caller lacks the write scope.
	//	UNAVAILABLE      — backend cannot accept writes.
	PutCredential(context.Context, *PutCredentialRequest) (*PutCredentialResponse, error)
	// RevokeCredential soft-deletes a non-current key_version. The adapter
	// refuses to revoke the current key_version (caller must rotate first).
	//
	// Errors:
	//
	//	FAILED_PRECONDITION — supplied key_version is the current one.
	//	NOT_FOUND           — no such version.
	RevokeCredential(context.Context, *RevokeCredentialRequest) (*RevokeCredentialResponse, error)
	// ListVersions returns metadata-only descriptors for all key_versions
	// of one (tenant_id, service_id). Plaintext is NEVER included.
	// Used by the Admin REST API and AdminJS for operator inspection.
	ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error)
	// ValidateServiceIdentity validates a per-service boot secret per ADR-0014.2.
	// Used by Admin API, MCP Server, Broker, and the proxy plugin to authenticate to
	// the Vault Adapter on startup.
	ValidateServiceIdentity(context.Context, *ValidateServiceIdentityRequest) (*ValidateServiceIdentityResponse, error)
	mustEmbedUnimplementedVaultAdapterServer()
}

// UnimplementedVaultAdapterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVaultAdapterServer struct{}

func (UnimplementedVaultAdapterServer) GetCredential(context.Context, *GetCredentialRequest) (*GetCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredential not implemented")
}
func (UnimplementedVaultAdapterServer) PutCredential(context.Context, *PutCredentialRequest) (*PutCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutCredential not implemented")
}
func (UnimplementedVaultAdapterServer) RevokeCredential(context.Context, *RevokeCredentialRequest) (*RevokeCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCredential not implemented")
}
func (UnimplementedVaultAdapterServer) ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVersions not implemented")
}
func (UnimplementedVaultAdapterServer) ValidateServiceIdentity(context.Context, *ValidateServiceIdentityRequest) (*ValidateServiceIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateServiceIdentity not implemented")
}
func (UnimplementedVaultAdapterServer) mustEmbedUnimplementedVaultAdapterServer() {}
func (UnimplementedVaultAdapterServer) testEmbeddedByValue()                      {}

// UnsafeVaultAdapterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaultAdapterServer will
// result in compilation errors.
type UnsafeVaultAdapterServer interface {
	mustEmbedUnimplementedVaultAdapterServer()
}

func RegisterVaultAdapterServer(s grpc.ServiceRegistrar, srv VaultAdapterServer) {
	// If the following call panics, it indicates UnimplementedVaultAdapterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VaultAdapter_ServiceDesc, srv)
}

func _VaultAdapter_GetCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultAdapterServer).GetCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultAdapter_GetCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultAdapterServer).GetCredential(ctx, req.(*GetCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultAdapter_PutCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultAdapterServer).PutCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultAdapter_PutCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultAdapterServer).PutCredential(ctx, req.(*PutCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultAdapter_RevokeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultAdapterServer).RevokeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultAdapter_RevokeCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultAdapterServer).RevokeCredential(ctx, req.(*RevokeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultAdapter_ListVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultAdapterServer).ListVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultAdapter_ListVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultAdapterServer).ListVersions(ctx, req.(*ListVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultAdapter_ValidateServiceIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateServiceIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultAdapterServer).ValidateServiceIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultAdapter_ValidateServiceIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultAdapterServer).ValidateServiceIdentity(ctx, req.(*ValidateServiceIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VaultAdapter_ServiceDesc is the grpc.ServiceDesc for VaultAdapter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaultAdapter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mintkey.vault.v1.VaultAdapter",
	HandlerType: (*VaultAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCredential",
			Handler:    _VaultAdapter_GetCredential_Handler,
		},
		{
			MethodName: "PutCredential",
			Handler:    _VaultAdapter_PutCredential_Handler,
		},
		{
			MethodName: "RevokeCredential",
			Handler:    _VaultAdapter_RevokeCredential_Handler,
		},
		{
			MethodName: "ListVersions",
			Handler:    _VaultAdapter_ListVersions_Handler,
		},
		{
			MethodName: "ValidateServiceIdentity",
			Handler:    _VaultAdapter_ValidateServiceIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}

const (
	AgentSecretsVault_PutAgentSecret_FullMethodName    = "/mintkey.vault.v1.AgentSecretsVault/PutAgentSecret"
	AgentSecretsVault_GetAgentSecret_FullMethodName    = "/mintkey.vault.v1.AgentSecretsVault/GetAgentSecret"
	AgentSecretsVault_DeleteAgentSecret_FullMethodName = "/mintkey.vault.v1.AgentSecretsVault/DeleteAgentSecret"
)

// AgentSecretsVaultClient is the client API for AgentSecretsVault service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentSecretsVault stores and retrieves agent-owned secrets (ADR-0025).
//
// Unlike VaultAdapter (keyed by tenant+service+key_version), this service
// is keyed by (tenant_id, secret_id) — one opaque ULID per secret write.
// Multiple secrets per agent are handled by SQL (public.agent_secrets);
// this service handles only the encrypted blob.
//
// Reuses crypto.Seal/Open and kek.Load from the vault-adapter package.
// Per-transaction set_config('app.current_tenant', …) and
// pg_advisory_xact_lock are applied identically to VaultAdapter.
//
// !! INTERNAL SERVICE !! Same trust boundary as VaultAdapter.
type AgentSecretsVaultClient interface {
	// PutAgentSecret seals the plaintext value and stores (or replaces)
	// the encrypted blob keyed by (tenant_id, secret_id).
	//
	// On overwrite the previous blob is replaced atomically.
	// The plaintext in the request is discarded after sealing.
	//
	// Errors:
	//
	//	INVALID_ARGUMENT  — tenant_id or secret_id is empty, or value
	//	                    exceeds 65536 bytes.
	//	PERMISSION_DENIED — caller lacks vault.secret.put scope.
	//	UNAVAILABLE       — Postgres backend unreachable.
	PutAgentSecret(ctx context.Context, in *PutAgentSecretRequest, opts ...grpc.CallOption) (*PutAgentSecretResponse, error)
	// GetAgentSecret unseals and returns the plaintext value for one
	// (tenant_id, secret_id). Every call should be accompanied by an
	// agent_secret.read audit event emitted by the MCP server.
	//
	// Errors:
	//
	//	NOT_FOUND         — no blob exists for (tenant_id, secret_id).
	//	PERMISSION_DENIED — caller lacks vault.secret.read scope.
	//	UNAVAILABLE       — Postgres backend unreachable.
	GetAgentSecret(ctx context.Context, in *GetAgentSecretRequest, opts ...grpc.CallOption) (*GetAgentSecretResponse, error)
	// DeleteAgentSecret removes the encrypted blob for (tenant_id, secret_id).
	// Idempotent: returns OK when the row is already absent.
	//
	// Errors:
	//
	//	PERMISSION_DENIED — caller lacks vault.secret.delete scope.
	//	UNAVAILABLE       — Postgres backend unreachable.
	DeleteAgentSecret(ctx context.Context, in *DeleteAgentSecretRequest, opts ...grpc.CallOption) (*DeleteAgentSecretResponse, error)
}

type agentSecretsVaultClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentSecretsVaultClient(cc grpc.ClientConnInterface) AgentSecretsVaultClient {
	return &agentSecretsVaultClient{cc}
}

func (c *agentSecretsVaultClient) PutAgentSecret(ctx context.Context, in *PutAgentSecretRequest, opts ...grpc.CallOption) (*PutAgentSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutAgentSecretResponse)
	err := c.cc.Invoke(ctx, AgentSecretsVault_PutAgentSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSecretsVaultClient) GetAgentSecret(ctx context.Context, in *GetAgentSecretRequest, opts ...grpc.CallOption) (*GetAgentSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentSecretResponse)
	err := c.cc.Invoke(ctx, AgentSecretsVault_GetAgentSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSecretsVaultClient) DeleteAgentSecret(ctx context.Context, in *DeleteAgentSecretRequest, opts ...grpc.CallOption) (*DeleteAgentSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAgentSecretResponse)
	err := c.cc.Invoke(ctx, AgentSecretsVault_DeleteAgentSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentSecretsVaultServer is the server API for AgentSecretsVault service.
// All implementations must embed UnimplementedAgentSecretsVaultServer
// for forward compatibility.
//
// AgentSecretsVault stores and retrieves agent-owned secrets (ADR-0025).
//
// Unlike VaultAdapter (keyed by tenant+service+key_version), this service
// is keyed by (tenant_id, secret_id) — one opaque ULID per secret write.
// Multiple secrets per agent are handled by SQL (public.agent_secrets);
// this service handles only the encrypted blob.
//
// Reuses crypto.Seal/Open and kek.Load from the vault-adapter package.
// Per-transaction set_config('app.current_tenant', …) and
// pg_advisory_xact_lock are applied identically to VaultAdapter.
//
// !! INTERNAL SERVICE !! Same trust boundary as VaultAdapter.
type AgentSecretsVaultServer interface {
	// PutAgentSecret seals the plaintext value and stores (or replaces)
	// the encrypted blob keyed by (tenant_id, secret_id).
	//
	// On overwrite the previous blob is replaced atomically.
	// The plaintext in the request is discarded after sealing.
	//
	// Errors:
	//
	//	INVALID_ARGUMENT  — tenant_id or secret_id is empty, or value
	//	                    exceeds 65536 bytes.
	//	PERMISSION_DENIED — caller lacks vault.secret.put scope.
	//	UNAVAILABLE       — Postgres backend unreachable.
	PutAgentSecret(context.Context, *PutAgentSecretRequest) (*PutAgentSecretResponse, error)
	// GetAgentSecret unseals and returns the plaintext value for one
	// (tenant_id, secret_id). Every call should be accompanied by an
	// agent_secret.read audit event emitted by the MCP server.
	//
	// Errors:
	//
	//	NOT_FOUND         — no blob exists for (tenant_id, secret_id).
	//	PERMISSION_DENIED — caller lacks vault.secret.read scope.
	//	UNAVAILABLE       — Postgres backend unreachable.
	GetAgentSecret(context.Context, *GetAgentSecretRequest) (*GetAgentSecretResponse, error)
	// DeleteAgentSecret removes the encrypted blob for (tenant_id, secret_id).
	// Idempotent: returns OK when the row is already absent.
	//
	// Errors:
	//
	//	PERMISSION_DENIED — caller lacks vault.secret.delete scope.
	//	UNAVAILABLE       — Postgres backend unreachable.
	DeleteAgentSecret(context.Context, *DeleteAgentSecretRequest) (*DeleteAgentSecretResponse, error)
	mustEmbedUnimplementedAgentSecretsVaultServer()
}

// UnimplementedAgentSecretsVaultServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentSecretsVaultServer struct{}

func (UnimplementedAgentSecretsVaultServer) PutAgentSecret(context.Context, *PutAgentSecretRequest) (*PutAgentSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutAgentSecret not implemented")
}
func (UnimplementedAgentSecretsVaultServer) GetAgentSecret(context.Context, *GetAgentSecretRequest) (*GetAgentSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentSecret not implemented")
}
func (UnimplementedAgentSecretsVaultServer) DeleteAgentSecret(context.Context, *DeleteAgentSecretRequest) (*DeleteAgentSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAgentSecret not implemented")
}
func (UnimplementedAgentSecretsVaultServer) mustEmbedUnimplementedAgentSecretsVaultServer() {}
func (UnimplementedAgentSecretsVaultServer) testEmbeddedByValue()                           {}

// UnsafeAgentSecretsVaultServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentSecretsVaultServer will
// result in compilation errors.
type UnsafeAgentSecretsVaultServer interface {
	mustEmbedUnimplementedAgentSecretsVaultServer()
}

func RegisterAgentSecretsVaultServer(s grpc.ServiceRegistrar, srv AgentSecretsVaultServer) {
	// If the following call panics, it indicates UnimplementedAgentSecretsVaultServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentSecretsVault_ServiceDesc, srv)
}

func _AgentSecretsVault_PutAgentSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAgentSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSecretsVaultServer).PutAgentSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSecretsVault_PutAgentSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSecretsVaultServer).PutAgentSecret(ctx, req.(*PutAgentSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSecretsVault_GetAgentSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSecretsVaultServer).GetAgentSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSecretsVault_GetAgentSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSecretsVaultServer).GetAgentSecret(ctx, req.(*GetAgentSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSecretsVault_DeleteAgentSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSecretsVaultServer).DeleteAgentSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSecretsVault_DeleteAgentSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSecretsVaultServer).DeleteAgentSecret(ctx, req.(*DeleteAgentSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentSecretsVault_ServiceDesc is the grpc.ServiceDesc for AgentSecretsVault service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentSecretsVault_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mintkey.vault.v1.AgentSecretsVault",
	HandlerType: (*AgentSecretsVaultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutAgentSecret",
			Handler:    _AgentSecretsVault_PutAgentSecret_Handler,
		},
		{
			MethodName: "GetAgentSecret",
			Handler:    _AgentSecretsVault_GetAgentSecret_Handler,
		},
		{
			MethodName: "DeleteAgentSecret",
			Handler:    _AgentSecretsVault_DeleteAgentSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}
