// vault.proto -- Mintkey Vault Adapter gRPC IDL.
//
// Stability tier: experimental.
// Version       : 0.1.0-preview.1.
//
// This service is the contract between every credential-aware Mintkey
// component and the Vault Adapter (container C6 in
// docs/01-architecture/02-container-view.md). The adapter is the only
// component that handles credential plaintext; consumers never persist
// plaintext returned by GetCredential and pass it only into per-request
// header injection (per ADR-0003).
//
// Per ADR-0008 (multi-tenancy), every operation is tenant-scoped; the
// adapter rejects requests whose tenant_id is empty or unknown.
//
// !! INTERNAL SERVICE !!
//   This gRPC service is NEVER exposed beyond the control plane's
//   trust boundary. It listens on a UDS or loopback gRPC endpoint with
//   mTLS in v1, with token-based authentication as a future option.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: vault.proto

package vaultv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthScheme mirrors the OpenAPI `AuthScheme` enum and the audit-event
// `auth_scheme` field. The two MUST stay in lockstep — adding a value
// here requires the same value in docs/contracts/rest/openapi.yaml.
type AuthScheme int32

const (
	AuthScheme_AUTH_SCHEME_UNSPECIFIED               AuthScheme = 0
	AuthScheme_AUTH_SCHEME_API_KEY_HEADER            AuthScheme = 1
	AuthScheme_AUTH_SCHEME_API_KEY_QUERY             AuthScheme = 2
	AuthScheme_AUTH_SCHEME_BEARER_TOKEN              AuthScheme = 3
	AuthScheme_AUTH_SCHEME_BASIC_AUTH                AuthScheme = 4
	AuthScheme_AUTH_SCHEME_OAUTH2_CLIENT_CREDENTIALS AuthScheme = 5
	AuthScheme_AUTH_SCHEME_OIDC_CLIENT_SECRET        AuthScheme = 6
	AuthScheme_AUTH_SCHEME_MTLS                      AuthScheme = 7
	AuthScheme_AUTH_SCHEME_OAUTH2_PASSWORD_GRANT     AuthScheme = 8
	// 9 is reserved for AUTH_SCHEME_APPLE_JWT (PR #134, not yet merged).
	AuthScheme_AUTH_SCHEME_GOOGLE_SERVICE_ACCOUNT AuthScheme = 10
)

// Enum value maps for AuthScheme.
var (
	AuthScheme_name = map[int32]string{
		0:  "AUTH_SCHEME_UNSPECIFIED",
		1:  "AUTH_SCHEME_API_KEY_HEADER",
		2:  "AUTH_SCHEME_API_KEY_QUERY",
		3:  "AUTH_SCHEME_BEARER_TOKEN",
		4:  "AUTH_SCHEME_BASIC_AUTH",
		5:  "AUTH_SCHEME_OAUTH2_CLIENT_CREDENTIALS",
		6:  "AUTH_SCHEME_OIDC_CLIENT_SECRET",
		7:  "AUTH_SCHEME_MTLS",
		8:  "AUTH_SCHEME_OAUTH2_PASSWORD_GRANT",
		10: "AUTH_SCHEME_GOOGLE_SERVICE_ACCOUNT",
	}
	AuthScheme_value = map[string]int32{
		"AUTH_SCHEME_UNSPECIFIED":               0,
		"AUTH_SCHEME_API_KEY_HEADER":            1,
		"AUTH_SCHEME_API_KEY_QUERY":             2,
		"AUTH_SCHEME_BEARER_TOKEN":              3,
		"AUTH_SCHEME_BASIC_AUTH":                4,
		"AUTH_SCHEME_OAUTH2_CLIENT_CREDENTIALS": 5,
		"AUTH_SCHEME_OIDC_CLIENT_SECRET":        6,
		"AUTH_SCHEME_MTLS":                      7,
		"AUTH_SCHEME_OAUTH2_PASSWORD_GRANT":     8,
		"AUTH_SCHEME_GOOGLE_SERVICE_ACCOUNT":    10,
	}
)

func (x AuthScheme) Enum() *AuthScheme {
	p := new(AuthScheme)
	*p = x
	return p
}

func (x AuthScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_vault_proto_enumTypes[0].Descriptor()
}

func (AuthScheme) Type() protoreflect.EnumType {
	return &file_vault_proto_enumTypes[0]
}

func (x AuthScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthScheme.Descriptor instead.
func (AuthScheme) EnumDescriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{0}
}

// CredentialStatus reflects the lifecycle of one (tenant_id, service_id,
// key_version) tuple.
type CredentialStatus int32

const (
	CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED CredentialStatus = 0
	CredentialStatus_CREDENTIAL_STATUS_ACTIVE      CredentialStatus = 1
	CredentialStatus_CREDENTIAL_STATUS_REVOKED     CredentialStatus = 2
)

// Enum value maps for CredentialStatus.
var (
	CredentialStatus_name = map[int32]string{
		0: "CREDENTIAL_STATUS_UNSPECIFIED",
		1: "CREDENTIAL_STATUS_ACTIVE",
		2: "CREDENTIAL_STATUS_REVOKED",
	}
	CredentialStatus_value = map[string]int32{
		"CREDENTIAL_STATUS_UNSPECIFIED": 0,
		"CREDENTIAL_STATUS_ACTIVE":      1,
		"CREDENTIAL_STATUS_REVOKED":     2,
	}
)

func (x CredentialStatus) Enum() *CredentialStatus {
	p := new(CredentialStatus)
	*p = x
	return p
}

func (x CredentialStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vault_proto_enumTypes[1].Descriptor()
}

func (CredentialStatus) Type() protoreflect.EnumType {
	return &file_vault_proto_enumTypes[1]
}

func (x CredentialStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialStatus.Descriptor instead.
func (CredentialStatus) EnumDescriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{1}
}

// GetCredentialRequest identifies a credential to fetch.
type GetCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ULID-prefixed tenant id (e.g. "tenant_01HX..."). REQUIRED.
	// Per ADR-0008 the adapter scopes every read to a tenant.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// ULID-prefixed service id (e.g. "svc_01HX..."). REQUIRED.
	ServiceId string `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// Specific key_version to fetch. Pass 0 to fetch the current version
	// (the adapter resolves the current version atomically).
	KeyVersion uint32 `protobuf:"varint,3,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	// Optional caller identifier (used for audit emission inside the
	// adapter). Format: any prefixed-ULID actor id.
	CallerActorId string `protobuf:"bytes,4,opt,name=caller_actor_id,json=callerActorId,proto3" json:"caller_actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialRequest) Reset() {
	*x = GetCredentialRequest{}
	mi := &file_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialRequest) ProtoMessage() {}

func (x *GetCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{0}
}

func (x *GetCredentialRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetCredentialRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GetCredentialRequest) GetKeyVersion() uint32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *GetCredentialRequest) GetCallerActorId() string {
	if x != nil {
		return x.CallerActorId
	}
	return ""
}

// GetCredentialResponse carries the plaintext value plus enough metadata
// for the proxy plugin to inject the credential per the auth scheme.
type GetCredentialResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The auth scheme dictates how the proxy injects `value`.
	AuthScheme AuthScheme `protobuf:"varint,1,opt,name=auth_scheme,json=authScheme,proto3,enum=mintkey.vault.v1.AuthScheme" json:"auth_scheme,omitempty"`
	// SENSITIVE — plaintext credential bytes. The proxy plugin holds this
	// in a request-scoped variable, injects it into the outbound request,
	// and discards. Never logged, never echoed in spans.
	//
	// Encoding by auth_scheme:
	//
	//	API_KEY_HEADER, API_KEY_QUERY, BEARER_TOKEN -> raw secret bytes
	//	BASIC_AUTH    -> "username:password" UTF-8 bytes
	//	OAUTH2_CLIENT_CREDENTIALS, OIDC_CLIENT_SECRET ->
	//	      JSON-encoded structured payload (see Cred*ClientSecret
	//	      schemas in docs/contracts/rest/openapi.yaml).
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Optional upstream expiry (e.g. for OAuth2 access tokens cached by
	// the adapter). Empty for static credentials.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// The version actually returned. Equals the request's key_version
	// unless that was 0 (then equals the current key_version).
	ReturnedKeyVersion uint32 `protobuf:"varint,4,opt,name=returned_key_version,json=returnedKeyVersion,proto3" json:"returned_key_version,omitempty"`
	// Current key_version at the time of the read. Useful for the proxy
	// plugin's cache invalidation logic.
	CurrentKeyVersion uint32 `protobuf:"varint,5,opt,name=current_key_version,json=currentKeyVersion,proto3" json:"current_key_version,omitempty"`
	// Optional injection hints for header/query schemes (e.g.
	// header_name="X-API-Key", query_param="api_key"). Set by the adapter
	// if the operator configured a non-default location.
	HeaderName string `protobuf:"bytes,6,opt,name=header_name,json=headerName,proto3" json:"header_name,omitempty"`
	QueryParam string `protobuf:"bytes,7,opt,name=query_param,json=queryParam,proto3" json:"query_param,omitempty"`
	// The registered base_url for the service (e.g. "https://api.twilio.com").
	// Stored alongside the credential so the proxy plugin never needs to trust
	// the caller-supplied X-Mintkey-Target header.
	TargetUrl     string `protobuf:"bytes,8,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialResponse) Reset() {
	*x = GetCredentialResponse{}
	mi := &file_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialResponse) ProtoMessage() {}

func (x *GetCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{1}
}

func (x *GetCredentialResponse) GetAuthScheme() AuthScheme {
	if x != nil {
		return x.AuthScheme
	}
	return AuthScheme_AUTH_SCHEME_UNSPECIFIED
}

func (x *GetCredentialResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetCredentialResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GetCredentialResponse) GetReturnedKeyVersion() uint32 {
	if x != nil {
		return x.ReturnedKeyVersion
	}
	return 0
}

func (x *GetCredentialResponse) GetCurrentKeyVersion() uint32 {
	if x != nil {
		return x.CurrentKeyVersion
	}
	return 0
}

func (x *GetCredentialResponse) GetHeaderName() string {
	if x != nil {
		return x.HeaderName
	}
	return ""
}

func (x *GetCredentialResponse) GetQueryParam() string {
	if x != nil {
		return x.QueryParam
	}
	return ""
}

func (x *GetCredentialResponse) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

// PutCredentialRequest creates a new credential version. Always
// monotonically advances key_version per (tenant_id, service_id).
type PutCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ULID-prefixed tenant id. REQUIRED.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// ULID-prefixed service id. REQUIRED.
	ServiceId string `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// Auth scheme of the credential. REQUIRED.
	AuthScheme AuthScheme `protobuf:"varint,3,opt,name=auth_scheme,json=authScheme,proto3,enum=mintkey.vault.v1.AuthScheme" json:"auth_scheme,omitempty"`
	// SENSITIVE — plaintext to store. Encoded per auth_scheme; same
	// encoding rules as GetCredentialResponse.value above.
	// Maximum size: 64 KiB.
	Value []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// Optional upstream expiry. Stored as-is; the adapter does not
	// refresh the credential on its own (refresh logic lives in the
	// adapter's per-scheme handler — covered in iteration-2 P-002 follow-up).
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Optional injection hints (header_name / query_param). Stored with
	// the credential metadata.
	HeaderName string `protobuf:"bytes,6,opt,name=header_name,json=headerName,proto3" json:"header_name,omitempty"`
	QueryParam string `protobuf:"bytes,7,opt,name=query_param,json=queryParam,proto3" json:"query_param,omitempty"`
	// Caller identifier for audit emission.
	CallerActorId string `protobuf:"bytes,8,opt,name=caller_actor_id,json=callerActorId,proto3" json:"caller_actor_id,omitempty"`
	// The service's registered base_url (e.g. "https://api.twilio.com").
	// Stored with the credential so GetCredential can return it to the proxy.
	TargetUrl     string `protobuf:"bytes,9,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutCredentialRequest) Reset() {
	*x = PutCredentialRequest{}
	mi := &file_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutCredentialRequest) ProtoMessage() {}

func (x *PutCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutCredentialRequest.ProtoReflect.Descriptor instead.
func (*PutCredentialRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{2}
}

func (x *PutCredentialRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PutCredentialRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *PutCredentialRequest) GetAuthScheme() AuthScheme {
	if x != nil {
		return x.AuthScheme
	}
	return AuthScheme_AUTH_SCHEME_UNSPECIFIED
}

func (x *PutCredentialRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutCredentialRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PutCredentialRequest) GetHeaderName() string {
	if x != nil {
		return x.HeaderName
	}
	return ""
}

func (x *PutCredentialRequest) GetQueryParam() string {
	if x != nil {
		return x.QueryParam
	}
	return ""
}

func (x *PutCredentialRequest) GetCallerActorId() string {
	if x != nil {
		return x.CallerActorId
	}
	return ""
}

func (x *PutCredentialRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

// PutCredentialResponse returns the new key_version.
type PutCredentialResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly assigned key_version.
	KeyVersion uint32 `protobuf:"varint,1,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	// Server-side creation timestamp (defensive-copy of the audit time).
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutCredentialResponse) Reset() {
	*x = PutCredentialResponse{}
	mi := &file_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutCredentialResponse) ProtoMessage() {}

func (x *PutCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutCredentialResponse.ProtoReflect.Descriptor instead.
func (*PutCredentialResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{3}
}

func (x *PutCredentialResponse) GetKeyVersion() uint32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *PutCredentialResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// RevokeCredentialRequest soft-deletes a non-current credential version.
type RevokeCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ULID-prefixed tenant id. REQUIRED.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// ULID-prefixed service id. REQUIRED.
	ServiceId string `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// The version to revoke. Refuses to revoke the current version.
	KeyVersion uint32 `protobuf:"varint,3,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	// Free-form reason string (recorded in the audit event payload).
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// Caller identifier for audit emission.
	CallerActorId string `protobuf:"bytes,5,opt,name=caller_actor_id,json=callerActorId,proto3" json:"caller_actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCredentialRequest) Reset() {
	*x = RevokeCredentialRequest{}
	mi := &file_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialRequest) ProtoMessage() {}

func (x *RevokeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialRequest.ProtoReflect.Descriptor instead.
func (*RevokeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeCredentialRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeCredentialRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RevokeCredentialRequest) GetKeyVersion() uint32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *RevokeCredentialRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevokeCredentialRequest) GetCallerActorId() string {
	if x != nil {
		return x.CallerActorId
	}
	return ""
}

// RevokeCredentialResponse confirms the revocation.
type RevokeCredentialResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Always set to CREDENTIAL_STATUS_REVOKED on success.
	Status CredentialStatus `protobuf:"varint,1,opt,name=status,proto3,enum=mintkey.vault.v1.CredentialStatus" json:"status,omitempty"`
	// Server-side revocation timestamp.
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCredentialResponse) Reset() {
	*x = RevokeCredentialResponse{}
	mi := &file_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialResponse) ProtoMessage() {}

func (x *RevokeCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialResponse.ProtoReflect.Descriptor instead.
func (*RevokeCredentialResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeCredentialResponse) GetStatus() CredentialStatus {
	if x != nil {
		return x.Status
	}
	return CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED
}

func (x *RevokeCredentialResponse) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

// ListVersionsRequest enumerates metadata-only descriptors for the
// versions of one (tenant_id, service_id).
type ListVersionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ULID-prefixed tenant id. REQUIRED.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// ULID-prefixed service id. REQUIRED.
	ServiceId string `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// Optional pagination — same semantics as the REST API: forward-only
	// cursor, exclusive of `after_key_version`.
	AfterKeyVersion uint32 `protobuf:"varint,3,opt,name=after_key_version,json=afterKeyVersion,proto3" json:"after_key_version,omitempty"`
	// Page size, 1..200, default 50.
	Limit uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Caller identifier for audit emission.
	CallerActorId string `protobuf:"bytes,5,opt,name=caller_actor_id,json=callerActorId,proto3" json:"caller_actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{6}
}

func (x *ListVersionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListVersionsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ListVersionsRequest) GetAfterKeyVersion() uint32 {
	if x != nil {
		return x.AfterKeyVersion
	}
	return 0
}

func (x *ListVersionsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVersionsRequest) GetCallerActorId() string {
	if x != nil {
		return x.CallerActorId
	}
	return ""
}

// VersionDescriptor is a metadata-only view of one credential version.
// NEVER carries plaintext.
type VersionDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ULID-prefixed credential id (cred_…).
	CredentialId string `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	// The key_version (monotonic per service).
	KeyVersion uint32 `protobuf:"varint,2,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	// True iff this is the current version of the credential.
	IsCurrent bool `protobuf:"varint,3,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	// Active or revoked.
	Status CredentialStatus `protobuf:"varint,4,opt,name=status,proto3,enum=mintkey.vault.v1.CredentialStatus" json:"status,omitempty"`
	// Auth scheme of the version.
	AuthScheme AuthScheme `protobuf:"varint,5,opt,name=auth_scheme,json=authScheme,proto3,enum=mintkey.vault.v1.AuthScheme" json:"auth_scheme,omitempty"`
	// KEK version that wrapped this DEK at write time. Used by the
	// operator to track KEK-rotation progress.
	KekVersion uint32 `protobuf:"varint,6,opt,name=kek_version,json=kekVersion,proto3" json:"kek_version,omitempty"`
	// Server-side timestamps.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RevokedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	// Optional upstream expiry.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionDescriptor) Reset() {
	*x = VersionDescriptor{}
	mi := &file_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionDescriptor) ProtoMessage() {}

func (x *VersionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionDescriptor.ProtoReflect.Descriptor instead.
func (*VersionDescriptor) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{7}
}

func (x *VersionDescriptor) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *VersionDescriptor) GetKeyVersion() uint32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *VersionDescriptor) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *VersionDescriptor) GetStatus() CredentialStatus {
	if x != nil {
		return x.Status
	}
	return CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED
}

func (x *VersionDescriptor) GetAuthScheme() AuthScheme {
	if x != nil {
		return x.AuthScheme
	}
	return AuthScheme_AUTH_SCHEME_UNSPECIFIED
}

func (x *VersionDescriptor) GetKekVersion() uint32 {
	if x != nil {
		return x.KekVersion
	}
	return 0
}

func (x *VersionDescriptor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VersionDescriptor) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *VersionDescriptor) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// ListVersionsResponse returns one page of version descriptors.
type ListVersionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The descriptors in increasing key_version order.
	Versions []*VersionDescriptor `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	// Next-page cursor. 0 indicates no further pages.
	NextAfterKeyVersion uint32 `protobuf:"varint,2,opt,name=next_after_key_version,json=nextAfterKeyVersion,proto3" json:"next_after_key_version,omitempty"`
	// Convenience field — the current key_version at query time.
	CurrentKeyVersion uint32 `protobuf:"varint,3,opt,name=current_key_version,json=currentKeyVersion,proto3" json:"current_key_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_vault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{8}
}

func (x *ListVersionsResponse) GetVersions() []*VersionDescriptor {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListVersionsResponse) GetNextAfterKeyVersion() uint32 {
	if x != nil {
		return x.NextAfterKeyVersion
	}
	return 0
}

func (x *ListVersionsResponse) GetCurrentKeyVersion() uint32 {
	if x != nil {
		return x.CurrentKeyVersion
	}
	return 0
}

// ValidateServiceIdentityRequest authenticates a calling service.
type ValidateServiceIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The service identity ID, e.g., svcid_admin_api, svcid_mcp, svcid_broker, svcid_proxy.
	ServiceIdentityId string `protobuf:"bytes,1,opt,name=service_identity_id,json=serviceIdentityId,proto3" json:"service_identity_id,omitempty"`
	// Raw 32-byte boot secret. Compared in constant time against the Argon2id hash stored
	// in the Vault Adapter under credential type 'service_identity'.
	Token         []byte `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateServiceIdentityRequest) Reset() {
	*x = ValidateServiceIdentityRequest{}
	mi := &file_vault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateServiceIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateServiceIdentityRequest) ProtoMessage() {}

func (x *ValidateServiceIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateServiceIdentityRequest.ProtoReflect.Descriptor instead.
func (*ValidateServiceIdentityRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateServiceIdentityRequest) GetServiceIdentityId() string {
	if x != nil {
		return x.ServiceIdentityId
	}
	return ""
}

func (x *ValidateServiceIdentityRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// ValidateServiceIdentityResponse describes whether the caller is authentic and what scopes apply.
type ValidateServiceIdentityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Policy scopes granted to this caller (e.g., "vault.read", "vault.put", "signing_key.read").
	Scopes []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// When the current boot secret expires (during a rotation overlap window). Optional.
	ValidUntil    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateServiceIdentityResponse) Reset() {
	*x = ValidateServiceIdentityResponse{}
	mi := &file_vault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateServiceIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateServiceIdentityResponse) ProtoMessage() {}

func (x *ValidateServiceIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateServiceIdentityResponse.ProtoReflect.Descriptor instead.
func (*ValidateServiceIdentityResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateServiceIdentityResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ValidateServiceIdentityResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ValidateServiceIdentityResponse) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

var File_vault_proto protoreflect.FileDescriptor

const file_vault_proto_rawDesc = "" +
	"\n" +
	"\vvault.proto\x12\x10mintkey.vault.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n" +
	"\x14GetCredentialRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vkey_version\x18\x03 \x01(\rR\n" +
	"keyVersion\x12&\n" +
	"\x0fcaller_actor_id\x18\x04 \x01(\tR\rcallerActorId\"\xea\x02\n" +
	"\x15GetCredentialResponse\x12=\n" +
	"\vauth_scheme\x18\x01 \x01(\x0e2\x1c.mintkey.vault.v1.AuthSchemeR\n" +
	"authScheme\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x120\n" +
	"\x14returned_key_version\x18\x04 \x01(\rR\x12returnedKeyVersion\x12.\n" +
	"\x13current_key_version\x18\x05 \x01(\rR\x11currentKeyVersion\x12\x1f\n" +
	"\vheader_name\x18\x06 \x01(\tR\n" +
	"headerName\x12\x1f\n" +
	"\vquery_param\x18\a \x01(\tR\n" +
	"queryParam\x12\x1d\n" +
	"\n" +
	"target_url\x18\b \x01(\tR\ttargetUrl\"\xeb\x02\n" +
	"\x14PutCredentialRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12=\n" +
	"\vauth_scheme\x18\x03 \x01(\x0e2\x1c.mintkey.vault.v1.AuthSchemeR\n" +
	"authScheme\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1f\n" +
	"\vheader_name\x18\x06 \x01(\tR\n" +
	"headerName\x12\x1f\n" +
	"\vquery_param\x18\a \x01(\tR\n" +
	"queryParam\x12&\n" +
	"\x0fcaller_actor_id\x18\b \x01(\tR\rcallerActorId\x12\x1d\n" +
	"\n" +
	"target_url\x18\t \x01(\tR\ttargetUrl\"s\n" +
	"\x15PutCredentialResponse\x12\x1f\n" +
	"\vkey_version\x18\x01 \x01(\rR\n" +
	"keyVersion\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb6\x01\n" +
	"\x17RevokeCredentialRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vkey_version\x18\x03 \x01(\rR\n" +
	"keyVersion\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12&\n" +
	"\x0fcaller_actor_id\x18\x05 \x01(\tR\rcallerActorId\"\x91\x01\n" +
	"\x18RevokeCredentialResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".mintkey.vault.v1.CredentialStatusR\x06status\x129\n" +
	"\n" +
	"revoked_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\xbb\x01\n" +
	"\x13ListVersionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12*\n" +
	"\x11after_key_version\x18\x03 \x01(\rR\x0fafterKeyVersion\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12&\n" +
	"\x0fcaller_actor_id\x18\x05 \x01(\tR\rcallerActorId\"\xc5\x03\n" +
	"\x11VersionDescriptor\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\x12\x1f\n" +
	"\vkey_version\x18\x02 \x01(\rR\n" +
	"keyVersion\x12\x1d\n" +
	"\n" +
	"is_current\x18\x03 \x01(\bR\tisCurrent\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".mintkey.vault.v1.CredentialStatusR\x06status\x12=\n" +
	"\vauth_scheme\x18\x05 \x01(\x0e2\x1c.mintkey.vault.v1.AuthSchemeR\n" +
	"authScheme\x12\x1f\n" +
	"\vkek_version\x18\x06 \x01(\rR\n" +
	"kekVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"revoked_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xbc\x01\n" +
	"\x14ListVersionsResponse\x12?\n" +
	"\bversions\x18\x01 \x03(\v2#.mintkey.vault.v1.VersionDescriptorR\bversions\x123\n" +
	"\x16next_after_key_version\x18\x02 \x01(\rR\x13nextAfterKeyVersion\x12.\n" +
	"\x13current_key_version\x18\x03 \x01(\rR\x11currentKeyVersion\"f\n" +
	"\x1eValidateServiceIdentityRequest\x12.\n" +
	"\x13service_identity_id\x18\x01 \x01(\tR\x11serviceIdentityId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\"\x86\x01\n" +
	"\x1fValidateServiceIdentityResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\x12;\n" +
	"\vvalid_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil*\xd6\x02\n" +
	"\n" +
	"AuthScheme\x12\x1b\n" +
	"\x17AUTH_SCHEME_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aAUTH_SCHEME_API_KEY_HEADER\x10\x01\x12\x1d\n" +
	"\x19AUTH_SCHEME_API_KEY_QUERY\x10\x02\x12\x1c\n" +
	"\x18AUTH_SCHEME_BEARER_TOKEN\x10\x03\x12\x1a\n" +
	"\x16AUTH_SCHEME_BASIC_AUTH\x10\x04\x12)\n" +
	"%AUTH_SCHEME_OAUTH2_CLIENT_CREDENTIALS\x10\x05\x12\"\n" +
	"\x1eAUTH_SCHEME_OIDC_CLIENT_SECRET\x10\x06\x12\x14\n" +
	"\x10AUTH_SCHEME_MTLS\x10\a\x12%\n" +
	"!AUTH_SCHEME_OAUTH2_PASSWORD_GRANT\x10\b\x12&\n" +
	"\"AUTH_SCHEME_GOOGLE_SERVICE_ACCOUNT\x10\n" +
	"*r\n" +
	"\x10CredentialStatus\x12!\n" +
	"\x1dCREDENTIAL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CREDENTIAL_STATUS_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19CREDENTIAL_STATUS_REVOKED\x10\x022\x9c\x04\n" +
	"\fVaultAdapter\x12`\n" +
	"\rGetCredential\x12&.mintkey.vault.v1.GetCredentialRequest\x1a'.mintkey.vault.v1.GetCredentialResponse\x12`\n" +
	"\rPutCredential\x12&.mintkey.vault.v1.PutCredentialRequest\x1a'.mintkey.vault.v1.PutCredentialResponse\x12i\n" +
	"\x10RevokeCredential\x12).mintkey.vault.v1.RevokeCredentialRequest\x1a*.mintkey.vault.v1.RevokeCredentialResponse\x12]\n" +
	"\fListVersions\x12%.mintkey.vault.v1.ListVersionsRequest\x1a&.mintkey.vault.v1.ListVersionsResponse\x12~\n" +
	"\x17ValidateServiceIdentity\x120.mintkey.vault.v1.ValidateServiceIdentityRequest\x1a1.mintkey.vault.v1.ValidateServiceIdentityResponseBM\n" +
	"\x13io.mintkey.vault.v1P\x01Z4github.com/mintkey/mintkey/internal/vault/v1;vaultv1b\x06proto3"

var (
	file_vault_proto_rawDescOnce sync.Once
	file_vault_proto_rawDescData []byte
)

func file_vault_proto_rawDescGZIP() []byte {
	file_vault_proto_rawDescOnce.Do(func() {
		file_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_proto_rawDesc), len(file_vault_proto_rawDesc)))
	})
	return file_vault_proto_rawDescData
}

var file_vault_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_vault_proto_goTypes = []any{
	(AuthScheme)(0),                         // 0: mintkey.vault.v1.AuthScheme
	(CredentialStatus)(0),                   // 1: mintkey.vault.v1.CredentialStatus
	(*GetCredentialRequest)(nil),            // 2: mintkey.vault.v1.GetCredentialRequest
	(*GetCredentialResponse)(nil),           // 3: mintkey.vault.v1.GetCredentialResponse
	(*PutCredentialRequest)(nil),            // 4: mintkey.vault.v1.PutCredentialRequest
	(*PutCredentialResponse)(nil),           // 5: mintkey.vault.v1.PutCredentialResponse
	(*RevokeCredentialRequest)(nil),         // 6: mintkey.vault.v1.RevokeCredentialRequest
	(*RevokeCredentialResponse)(nil),        // 7: mintkey.vault.v1.RevokeCredentialResponse
	(*ListVersionsRequest)(nil),             // 8: mintkey.vault.v1.ListVersionsRequest
	(*VersionDescriptor)(nil),               // 9: mintkey.vault.v1.VersionDescriptor
	(*ListVersionsResponse)(nil),            // 10: mintkey.vault.v1.ListVersionsResponse
	(*ValidateServiceIdentityRequest)(nil),  // 11: mintkey.vault.v1.ValidateServiceIdentityRequest
	(*ValidateServiceIdentityResponse)(nil), // 12: mintkey.vault.v1.ValidateServiceIdentityResponse
	(*timestamppb.Timestamp)(nil),           // 13: google.protobuf.Timestamp
}
var file_vault_proto_depIdxs = []int32{
	0,  // 0: mintkey.vault.v1.GetCredentialResponse.auth_scheme:type_name -> mintkey.vault.v1.AuthScheme
	13, // 1: mintkey.vault.v1.GetCredentialResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 2: mintkey.vault.v1.PutCredentialRequest.auth_scheme:type_name -> mintkey.vault.v1.AuthScheme
	13, // 3: mintkey.vault.v1.PutCredentialRequest.expires_at:type_name -> google.protobuf.Timestamp
	13, // 4: mintkey.vault.v1.PutCredentialResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 5: mintkey.vault.v1.RevokeCredentialResponse.status:type_name -> mintkey.vault.v1.CredentialStatus
	13, // 6: mintkey.vault.v1.RevokeCredentialResponse.revoked_at:type_name -> google.protobuf.Timestamp
	1,  // 7: mintkey.vault.v1.VersionDescriptor.status:type_name -> mintkey.vault.v1.CredentialStatus
	0,  // 8: mintkey.vault.v1.VersionDescriptor.auth_scheme:type_name -> mintkey.vault.v1.AuthScheme
	13, // 9: mintkey.vault.v1.VersionDescriptor.created_at:type_name -> google.protobuf.Timestamp
	13, // 10: mintkey.vault.v1.VersionDescriptor.revoked_at:type_name -> google.protobuf.Timestamp
	13, // 11: mintkey.vault.v1.VersionDescriptor.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 12: mintkey.vault.v1.ListVersionsResponse.versions:type_name -> mintkey.vault.v1.VersionDescriptor
	13, // 13: mintkey.vault.v1.ValidateServiceIdentityResponse.valid_until:type_name -> google.protobuf.Timestamp
	2,  // 14: mintkey.vault.v1.VaultAdapter.GetCredential:input_type -> mintkey.vault.v1.GetCredentialRequest
	4,  // 15: mintkey.vault.v1.VaultAdapter.PutCredential:input_type -> mintkey.vault.v1.PutCredentialRequest
	6,  // 16: mintkey.vault.v1.VaultAdapter.RevokeCredential:input_type -> mintkey.vault.v1.RevokeCredentialRequest
	8,  // 17: mintkey.vault.v1.VaultAdapter.ListVersions:input_type -> mintkey.vault.v1.ListVersionsRequest
	11, // 18: mintkey.vault.v1.VaultAdapter.ValidateServiceIdentity:input_type -> mintkey.vault.v1.ValidateServiceIdentityRequest
	3,  // 19: mintkey.vault.v1.VaultAdapter.GetCredential:output_type -> mintkey.vault.v1.GetCredentialResponse
	5,  // 20: mintkey.vault.v1.VaultAdapter.PutCredential:output_type -> mintkey.vault.v1.PutCredentialResponse
	7,  // 21: mintkey.vault.v1.VaultAdapter.RevokeCredential:output_type -> mintkey.vault.v1.RevokeCredentialResponse
	10, // 22: mintkey.vault.v1.VaultAdapter.ListVersions:output_type -> mintkey.vault.v1.ListVersionsResponse
	12, // 23: mintkey.vault.v1.VaultAdapter.ValidateServiceIdentity:output_type -> mintkey.vault.v1.ValidateServiceIdentityResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_vault_proto_init() }
func file_vault_proto_init() {
	if File_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_proto_rawDesc), len(file_vault_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_proto_goTypes,
		DependencyIndexes: file_vault_proto_depIdxs,
		EnumInfos:         file_vault_proto_enumTypes,
		MessageInfos:      file_vault_proto_msgTypes,
	}.Build()
	File_vault_proto = out.File
	file_vault_proto_goTypes = nil
	file_vault_proto_depIdxs = nil
}
