#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# e2e-setup-env.sh — Extract live-stack credentials into Playwright .env.local
#
# Reads the bootstrap password from the seed-job secret, queries Postgres
# for the default tenant + operator IDs, and writes .env.local so the
# Playwright tests can run against the running compose stack.
#
# Usage:  ./scripts/e2e-setup-env.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
E2E_DIR="${REPO_ROOT}/admin-ui/e2e"
ENV_FILE="${E2E_DIR}/.env.local"

echo "═══════════════════════════════════════════════════════════════"
echo "  Mintkey E2E Playwright — Environment Setup"
echo "═══════════════════════════════════════════════════════════════"

# ── 1. Verify docker compose is running ────────────────────────────────────────
echo ""
echo "▸ Checking docker compose stack …"
RUNNING=$(docker compose ps --format json 2>/dev/null | jq -r 'any(.[].State; . == "running")' 2>/dev/null || echo "false")
if [[ "$RUNNING" != "true" ]]; then
  echo "  Stack not running — starting it now (this may take a while)…"
  docker compose up -d --wait 2>&1 | tail -5
else
  echo "  Stack is already running."
fi

# ── 2. Wait for services to be healthy ─────────────────────────────────────────
echo ""
echo "▸ Waiting for admin-api and admin-ui healthchecks …"
MAX_WAIT=60
ELAPSED=0
while true; do
  API_OK=$(curl -sf http://localhost:8080/v1/health 2>/dev/null && echo "ok" || echo "fail")
  UI_OK=$(curl -sf http://localhost:8081/health 2>/dev/null && echo "ok" || echo "fail")

  if [[ "$API_OK" == "ok" && "$UI_OK" == "ok" ]]; then
    echo "  ✅ admin-api and admin-ui are healthy"
    break
  fi

  if [[ $ELAPSED -ge $MAX_WAIT ]]; then
    echo "  ❌ Timeout waiting for services (after ${MAX_WAIT}s)"
    echo "     admin-api health: $API_OK"
    echo "     admin-ui health:  $UI_OK"
    exit 1
  fi

  sleep 2
  ELAPSED=$((ELAPSED + 2))
  echo -ne "  ⏳ waiting … (${ELAPSED}s / ${MAX_WAIT}s)\r"
done

# ── 3. Extract bootstrap credentials ──────────────────────────────────────────
echo ""
echo "▸ Extracting bootstrap credentials …"

BOOTSTRAP_PW_FILE="${REPO_ROOT}/data/bootstrap-secrets/admin_password"
if [[ ! -f "$BOOTSTRAP_PW_FILE" ]]; then
  echo "  ❌ Cannot find $BOOTSTRAP_PW_FILE"
  echo "     Run 'make dev' first and ensure the seed-job has completed."
  exit 1
fi
# The file contains Fernet-encrypted ciphertext (S6 — CodeQL cleartext-storage
# remediation).  Decrypt using the same MINTKEY_BOOTSTRAP_KEK that the seed-job
# used to encrypt.  Falls back to the docker-compose default dev key if unset.
_KEK="${MINTKEY_BOOTSTRAP_KEK:-TUQpz9CUkfOvVJiM0yBUL8J9xAgrzE__JkNnwcocVas=}"
ADMIN_PASS="$(python3 - "$BOOTSTRAP_PW_FILE" "$_KEK" <<'PYEOF'
import sys
from cryptography.fernet import Fernet
pw_file, kek = sys.argv[1], sys.argv[2]
ciphertext = open(pw_file, "rb").read()
print(Fernet(kek.encode()).decrypt(ciphertext).decode().strip())
PYEOF
)"
echo "  ✅ Admin password decrypted from seed secret"

# ── 4. Query Postgres for tenant & operator IDs ───────────────────────────────
echo ""
echo "▸ Querying Postgres for tenant and operator IDs …"

export PGPASSWORD="changeme"
TENANT_ID=$(docker compose exec -T postgres psql -U mintkey_migrate -d mintkey -t -A -c "
  SELECT id FROM tenants WHERE slug = 't_default' LIMIT 1;
" 2>/dev/null | tr -d '[:space:]')

if [[ -z "$TENANT_ID" ]]; then
  echo "  ❌ Could not find default tenant in database"
  exit 1
fi
echo "  ✅ Tenant ID: $TENANT_ID"

OPERATOR_ID=$(docker compose exec -T postgres psql -U mintkey_migrate -d mintkey -t -A -c "
  SELECT id FROM operators WHERE email = 'admin@mintkey.internal' LIMIT 1;
" 2>/dev/null | tr -d '[:space:]')
echo "  ✅ Operator ID: $OPERATOR_ID"

# ── 5. Write .env.local ────────────────────────────────────────────────────────
echo ""
echo "▸ Writing ${ENV_FILE} …"

cat > "${ENV_FILE}" <<ENVEOF
# Auto-generated by scripts/e2e-setup-env.sh — do not commit
PLAYWRIGHT_BASE_URL=http://localhost:8081
PLAYWRIGHT_USER=admin@mintkey.internal
PLAYWRIGHT_PASS=${ADMIN_PASS}
PLAYWRIGHT_TENANT_ID=${TENANT_ID}
PLAYWRIGHT_OPERATOR_ID=${OPERATOR_ID}
PLAYWRIGHT_IS_PLATFORM_ADMIN=true
ADMIN_API_URL=http://localhost:8080
ENVEOF

chmod 600 "${ENV_FILE}"
echo "  ✅ .env.local written"

# ── 6. Install Playwright deps if needed ──────────────────────────────────────
echo ""
echo "▸ Checking Playwright dependencies …"
cd "${E2E_DIR}"

if [[ ! -d "node_modules/@playwright/test" ]]; then
  echo "  Installing Playwright test runner …"
  pnpm install 2>&1 | tail -5
else
  echo "  ✅ Playwright already installed"
fi

# Check if Chromium browser is installed
CHROMIUM_DIR="${E2E_DIR}/node_modules/.cache/playwright/chromium-1155"
if [[ ! -d "$CHROMIUM_DIR" ]]; then
  echo "  Installing Chromium browser …"
  npx playwright install --with-deps chromium 2>&1 | tail -5
else
  echo "  ✅ Chromium browser already installed"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  ✅ Setup complete. Run one of:"
echo "     make test:e2e          — headless (all browsers)"
echo "     make test:e2e:headed   — headed mode (debug)"
echo "     make test:e2e:ci       — CI mode (Chromium + retries)"
echo "═══════════════════════════════════════════════════════════════"