// Package sshvault defines the wire types and gRPC service descriptor for the
// three SSH-proxy-specific vault RPCs (ADR-0021, chunk C7).
//
// These types are NOT generated by protoc — they use encoding/json over raw
// gRPC bytes to avoid requiring a protoc toolchain in CI. The contract is:
//
//	Content-Type: application/grpc
//	Encoding:     JSON-in-length-prefixed-gRPC-frame
//
// Both the vault-adapter server (this package) and the ssh-proxy client
// (apps/ssh-proxy/internal/vault/client.go) must import the same codec. The
// codec is registered once via init() in codec.go using grpc.RegisterCodec.
//
// Method names (full gRPC paths):
//
//	/mintkey.vault.v1.SSHVaultAdapter/GetAgentByFingerprint
//	/mintkey.vault.v1.SSHVaultAdapter/GetHostKeyFingerprint
//	/mintkey.vault.v1.SSHVaultAdapter/StoreHostKeyFingerprint
//
// Source: ADR-0021; chunk C7.
package sshvault

// GetAgentByFingerprintRequest carries the SHA-256 SSH public-key fingerprint
// (OpenSSH format, e.g. "SHA256:abc...").
type GetAgentByFingerprintRequest struct {
	// Fingerprint is the SHA-256 fingerprint of the agent's SSH public key
	// as produced by ssh.FingerprintSHA256 (e.g. "SHA256:abc...").
	Fingerprint string `json:"fingerprint"`
}

// GetAgentByFingerprintResponse returns the matching agent details.
type GetAgentByFingerprintResponse struct {
	AgentID   string `json:"agent_id"`
	TenantID  string `json:"tenant_id"`
	Name      string `json:"name"`
	SSHPubKey string `json:"ssh_pubkey"`
	Status    string `json:"status"`
}

// HostKeyFingerprintRequest identifies a (tenant, service) pair for host-key lookup.
type HostKeyFingerprintRequest struct {
	TenantID  string `json:"tenant_id"`
	ServiceID string `json:"service_id"`
}

// HostKeyFingerprintResponse returns the stored fingerprint, or empty string if
// no key has been seen yet.
type HostKeyFingerprintResponse struct {
	// Fingerprint is the stored SHA-256 fingerprint, or "" if none recorded.
	Fingerprint string `json:"fingerprint"`
}

// StoreHostKeyFingerprintRequest persists a host-key fingerprint for TOFU.
type StoreHostKeyFingerprintRequest struct {
	TenantID    string `json:"tenant_id"`
	ServiceID   string `json:"service_id"`
	Fingerprint string `json:"fingerprint"`
}

// StoreHostKeyFingerprintResponse is an empty acknowledgement.
type StoreHostKeyFingerprintResponse struct{}
