#!/usr/bin/env bash
# spec-trace.sh — generate ADR/contract traceability matrix
# Output: .spec-trace/matrix.md
# Exit 0: clean. Exit 1: gaps found.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$REPO_ROOT/.spec-trace"
OUT="$OUT_DIR/matrix.md"
mkdir -p "$OUT_DIR"
GAPS=0

echo "=== Spec Trace ==="
echo

{
  echo "# Spec Traceability Matrix"
  echo
  echo "> Generated by \`make spec-trace\`. Do not edit manually."
  echo
  echo "## ADRs"
  echo
  echo "| ADR | Referenced in tests | Referenced in code |"
  echo "|---|---|---|"

  adr_dir="$REPO_ROOT/docs/architecture/adrs"
  if [[ -d "$adr_dir" ]]; then
    while IFS= read -r adr; do
      slug="$(basename "$adr" .md)"
      in_tests=$(grep -rl "$slug" "$REPO_ROOT/tests" 2>/dev/null | wc -l | tr -d ' ')
      in_code=$(grep -rl "$slug" "$REPO_ROOT" --include="*.py" --include="*.ts" --include="*.go" --include="*.java" 2>/dev/null | wc -l | tr -d ' ')
      echo "| $slug | $in_tests | $in_code |"
    done < <(find "$adr_dir" -name "*.md" ! -name ".gitkeep" 2>/dev/null | sort)
  fi

  echo
  echo "## Contracts"
  echo
  echo "| Contract | Has fixtures | Referenced in tests |"
  echo "|---|---|---|"

  for contract_dir in openapi asyncapi jsonschema; do
    dir="$REPO_ROOT/contracts/$contract_dir"
    [[ ! -d "$dir" ]] && continue
    while IFS= read -r cf; do
      slug="$(basename "$cf")"
      has_fixture=$(grep -rl "$(basename "$cf" .yaml)" "$REPO_ROOT/contracts/fixtures" 2>/dev/null | wc -l | tr -d ' ')
      in_tests=$(grep -rl "$(basename "$cf" .yaml)" "$REPO_ROOT/tests" 2>/dev/null | wc -l | tr -d ' ')
      echo "| contracts/$contract_dir/$slug | $has_fixture | $in_tests |"
    done < <(find "$dir" -name "*.yaml" -o -name "*.json" 2>/dev/null | sort)
  done
} > "$OUT"

echo "Written: $OUT"
echo
if [[ $GAPS -gt 0 ]]; then
  echo "⚠ $GAPS gap(s) found. Review $OUT."
  exit 1
else
  echo "✓ Matrix generated."
  exit 0
fi
