# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from admin_api.services import vault_pb2 as vault__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vault_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VaultAdapterStub(object):
    """VaultAdapter is the credential storage interface. Backends are
    pluggable per ADR-0003 (file in v1; HashiCorp Vault in v2; SQL+KMS in
    v3); all backends expose this same interface.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCredential = channel.unary_unary(
                '/mintkey.vault.v1.VaultAdapter/GetCredential',
                request_serializer=vault__pb2.GetCredentialRequest.SerializeToString,
                response_deserializer=vault__pb2.GetCredentialResponse.FromString,
                _registered_method=True)
        self.PutCredential = channel.unary_unary(
                '/mintkey.vault.v1.VaultAdapter/PutCredential',
                request_serializer=vault__pb2.PutCredentialRequest.SerializeToString,
                response_deserializer=vault__pb2.PutCredentialResponse.FromString,
                _registered_method=True)
        self.RevokeCredential = channel.unary_unary(
                '/mintkey.vault.v1.VaultAdapter/RevokeCredential',
                request_serializer=vault__pb2.RevokeCredentialRequest.SerializeToString,
                response_deserializer=vault__pb2.RevokeCredentialResponse.FromString,
                _registered_method=True)
        self.ListVersions = channel.unary_unary(
                '/mintkey.vault.v1.VaultAdapter/ListVersions',
                request_serializer=vault__pb2.ListVersionsRequest.SerializeToString,
                response_deserializer=vault__pb2.ListVersionsResponse.FromString,
                _registered_method=True)
        self.ValidateServiceIdentity = channel.unary_unary(
                '/mintkey.vault.v1.VaultAdapter/ValidateServiceIdentity',
                request_serializer=vault__pb2.ValidateServiceIdentityRequest.SerializeToString,
                response_deserializer=vault__pb2.ValidateServiceIdentityResponse.FromString,
                _registered_method=True)


class VaultAdapterServicer(object):
    """VaultAdapter is the credential storage interface. Backends are
    pluggable per ADR-0003 (file in v1; HashiCorp Vault in v2; SQL+KMS in
    v3); all backends expose this same interface.
    """

    def GetCredential(self, request, context):
        """GetCredential returns the plaintext credential value for one
        (tenant_id, service_id, key_version) tuple. Used by the Egress
        Proxy plugin (per ADR-0004) on every brokered request.

        Pass key_version = 0 to fetch the current credential version
        (atomic relative to a credential.rotated event).

        Errors:
        NOT_FOUND       — no credential exists for the tuple.
        PERMISSION_DENIED — caller lacks the read scope for the tenant.
        FAILED_PRECONDITION — credential is revoked.
        UNAVAILABLE     — backend (file/Vault/KMS) is unreachable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutCredential(self, request, context):
        """PutCredential creates or rotates a credential. The adapter assigns
        a new monotonic key_version per (tenant_id, service_id) and returns
        it. The plaintext sent in the request lives in the adapter's memory
        for the duration of the call, is sealed with a fresh DEK, and is
        discarded; the cleartext value is NEVER persisted or logged.

        Errors:
        INVALID_ARGUMENT — auth_scheme/value mismatch, missing required
        fields, or value too large.
        PERMISSION_DENIED — caller lacks the write scope.
        UNAVAILABLE      — backend cannot accept writes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeCredential(self, request, context):
        """RevokeCredential soft-deletes a non-current key_version. The adapter
        refuses to revoke the current key_version (caller must rotate first).

        Errors:
        FAILED_PRECONDITION — supplied key_version is the current one.
        NOT_FOUND           — no such version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVersions(self, request, context):
        """ListVersions returns metadata-only descriptors for all key_versions
        of one (tenant_id, service_id). Plaintext is NEVER included.
        Used by the Admin REST API and AdminJS for operator inspection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateServiceIdentity(self, request, context):
        """ValidateServiceIdentity validates a per-service boot secret per ADR-0014.2.
        Used by Admin API, MCP Server, Broker, and the proxy plugin to authenticate to
        the Vault Adapter on startup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VaultAdapterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredential,
                    request_deserializer=vault__pb2.GetCredentialRequest.FromString,
                    response_serializer=vault__pb2.GetCredentialResponse.SerializeToString,
            ),
            'PutCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.PutCredential,
                    request_deserializer=vault__pb2.PutCredentialRequest.FromString,
                    response_serializer=vault__pb2.PutCredentialResponse.SerializeToString,
            ),
            'RevokeCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeCredential,
                    request_deserializer=vault__pb2.RevokeCredentialRequest.FromString,
                    response_serializer=vault__pb2.RevokeCredentialResponse.SerializeToString,
            ),
            'ListVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVersions,
                    request_deserializer=vault__pb2.ListVersionsRequest.FromString,
                    response_serializer=vault__pb2.ListVersionsResponse.SerializeToString,
            ),
            'ValidateServiceIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateServiceIdentity,
                    request_deserializer=vault__pb2.ValidateServiceIdentityRequest.FromString,
                    response_serializer=vault__pb2.ValidateServiceIdentityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mintkey.vault.v1.VaultAdapter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mintkey.vault.v1.VaultAdapter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VaultAdapter(object):
    """VaultAdapter is the credential storage interface. Backends are
    pluggable per ADR-0003 (file in v1; HashiCorp Vault in v2; SQL+KMS in
    v3); all backends expose this same interface.
    """

    @staticmethod
    def GetCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mintkey.vault.v1.VaultAdapter/GetCredential',
            vault__pb2.GetCredentialRequest.SerializeToString,
            vault__pb2.GetCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mintkey.vault.v1.VaultAdapter/PutCredential',
            vault__pb2.PutCredentialRequest.SerializeToString,
            vault__pb2.PutCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mintkey.vault.v1.VaultAdapter/RevokeCredential',
            vault__pb2.RevokeCredentialRequest.SerializeToString,
            vault__pb2.RevokeCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mintkey.vault.v1.VaultAdapter/ListVersions',
            vault__pb2.ListVersionsRequest.SerializeToString,
            vault__pb2.ListVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateServiceIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mintkey.vault.v1.VaultAdapter/ValidateServiceIdentity',
            vault__pb2.ValidateServiceIdentityRequest.SerializeToString,
            vault__pb2.ValidateServiceIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
