// Package wireids_test provides cross-language golden tests for DBUUIDToWire.
//
// Golden vectors were generated by the canonical Python encoder:
//
//	python3 -c "
//	import sys; sys.path.insert(0,'admin-api/src')
//	from admin_api.utils.wire_ids import db_uuid_to_wire
//	import uuid
//	pairs = [
//	  ('6c3c950a-2e18-4ba9-8c89-5b875b1bf5bd', 'svc'),
//	  ('00000000-0000-0000-0000-000000000000', 'svc'),
//	  ('ffffffff-ffff-ffff-ffff-ffffffffffff', 'svc'),
//	  ('12345678-1234-5678-1234-567812345678', 'svc'),
//	  ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'svc'),
//	  ('deadbeef-dead-beef-dead-beefdeadbeef', 'svc'),
//	  ('00000000-0000-0000-0000-000000000001', 'svc'),
//	  ('cafebabe-cafe-babe-cafe-babecafebabe', 'svc'),
//	]
//	for u, pfx in pairs:
//	    print(db_uuid_to_wire(u, pfx))
//	"
//
// Output confirmed:
//
//	svc_3C7JAGMBGR9EMRS2AVGXDHQXDX
//	svc_00000000000000000000000000
//	svc_7ZZZZZZZZZZZZZZZZZZZZZZZZZ
//	svc_0J6HB7G4HMASW14D2PF0938NKR
//	svc_51PB1X9SFPF28AQKFF28T5CY4G
//	svc_6YNPZEZQNDQVQXXBDYXZFAVFQF
//	svc_00000000000000000000000001
//	svc_6AZTXBXJQYQAZCNZNTQV5FXENY
//
// Source: ADR-0017.11; OPS-GG.
package wireids_test

import (
	"strings"
	"testing"

	"github.com/mintkey/mintkey/services/kong-syncer/internal/wireids"
)

// goldenPair is a UUID ↔ expected-wire-form test vector.
type goldenPair struct {
	uuid   string
	prefix string
	want   string
}

// goldenVectors are cross-language test vectors locked in from the Python
// encoder (admin-api/src/admin_api/utils/wire_ids.py).  DO NOT modify without
// regenerating from the Python source.
var goldenVectors = []goldenPair{
	// The docstring example from wire_ids.py — primary correctness anchor.
	{"6c3c950a-2e18-4ba9-8c89-5b875b1bf5bd", "svc", "svc_3C7JAGMBGR9EMRS2AVGXDHQXDX"},
	// All-zeros UUID → all-zeros wire form.
	{"00000000-0000-0000-0000-000000000000", "svc", "svc_00000000000000000000000000"},
	// All-ones UUID → max wire form.
	{"ffffffff-ffff-ffff-ffff-ffffffffffff", "svc", "svc_7ZZZZZZZZZZZZZZZZZZZZZZZZZ"},
	// Incrementing hex pattern.
	{"12345678-1234-5678-1234-567812345678", "svc", "svc_0J6HB7G4HMASW14D2PF0938NKR"},
	// Mixed-case hex in canonical UUID form.
	{"a1b2c3d4-e5f6-7890-abcd-ef1234567890", "svc", "svc_51PB1X9SFPF28AQKFF28T5CY4G"},
	// "deadbeef" pattern.
	{"deadbeef-dead-beef-dead-beefdeadbeef", "svc", "svc_6YNPZEZQNDQVQXXBDYXZFAVFQF"},
	// Minimal non-zero UUID (only LSB set) → last digit is 1.
	{"00000000-0000-0000-0000-000000000001", "svc", "svc_00000000000000000000000001"},
	// "cafebabe" pattern.
	{"cafebabe-cafe-babe-cafe-babecafebabe", "svc", "svc_6AZTXBXJQYQAZCNZNTQV5FXENY"},
}

// TestDBUUIDToWire_GoldenVectors locks in bit-exact parity with the Python encoder.
// A failure here means the Go and Python encoders have diverged and the proxy
// will return 404 for any route whose svc_ ID was computed by the other side.
func TestDBUUIDToWire_GoldenVectors(t *testing.T) {
	for _, tc := range goldenVectors {
		got, err := wireids.DBUUIDToWire(tc.uuid, tc.prefix)
		if err != nil {
			t.Errorf("DBUUIDToWire(%q, %q): unexpected error: %v", tc.uuid, tc.prefix, err)
			continue
		}
		if got != tc.want {
			t.Errorf("DBUUIDToWire(%q, %q)\n  got  %q\n  want %q", tc.uuid, tc.prefix, got, tc.want)
		}
	}
}

// TestDBUUIDToWire_OutputShape verifies the structural invariants of every output.
func TestDBUUIDToWire_OutputShape(t *testing.T) {
	for _, tc := range goldenVectors {
		got, err := wireids.DBUUIDToWire(tc.uuid, tc.prefix)
		if err != nil {
			t.Errorf("DBUUIDToWire(%q, %q): unexpected error: %v", tc.uuid, tc.prefix, err)
			continue
		}

		// Must be <prefix>_<26 chars> = prefix + 1 + 26 = 30 chars for "svc".
		expectedLen := len(tc.prefix) + 1 + 26
		if len(got) != expectedLen {
			t.Errorf("DBUUIDToWire(%q, %q): length = %d, want %d (got %q)", tc.uuid, tc.prefix, len(got), expectedLen, got)
		}

		// Must start with <prefix>_.
		expectedPrefix := tc.prefix + "_"
		if !strings.HasPrefix(got, expectedPrefix) {
			t.Errorf("DBUUIDToWire(%q, %q): missing prefix %q in %q", tc.uuid, tc.prefix, expectedPrefix, got)
		}

		// The 26-char token must only contain Crockford alphabet chars.
		const crockfordAlpha = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
		token := got[len(expectedPrefix):]
		for _, ch := range token {
			if !strings.ContainsRune(crockfordAlpha, ch) {
				t.Errorf("DBUUIDToWire(%q, %q): non-Crockford char %q in token %q", tc.uuid, tc.prefix, ch, token)
			}
		}
	}
}

// TestDBUUIDToWire_InvalidInputs confirms that malformed UUIDs return errors.
func TestDBUUIDToWire_InvalidInputs(t *testing.T) {
	bad := []string{
		"",
		"not-a-uuid",
		"6c3c950a-2e18-4ba9-8c89",         // too short
		"6c3c950a-2e18-4ba9-8c89-5b875b1bf5bd-extra", // too long
		"6c3c950a-2e18-4ba9-8c89-ZZZZZZZZZZZZ",        // invalid hex
	}
	for _, u := range bad {
		_, err := wireids.DBUUIDToWire(u, "svc")
		if err == nil {
			t.Errorf("DBUUIDToWire(%q, svc): expected error, got nil", u)
		}
	}
}

// TestDBUUIDToWire_DashedAndHexFormEquivalent confirms that the dashed and
// no-dash forms of the same UUID produce identical output.
func TestDBUUIDToWire_DashedAndHexFormEquivalent(t *testing.T) {
	dashed := "6c3c950a-2e18-4ba9-8c89-5b875b1bf5bd"
	nodash := "6c3c950a2e184ba98c895b875b1bf5bd"

	wDashed, err1 := wireids.DBUUIDToWire(dashed, "svc")
	wNodash, err2 := wireids.DBUUIDToWire(nodash, "svc")

	if err1 != nil {
		t.Fatalf("dashed form: %v", err1)
	}
	if err2 != nil {
		t.Fatalf("no-dash form: %v", err2)
	}
	if wDashed != wNodash {
		t.Errorf("dashed %q and no-dash %q produced different outputs:\n  dashed: %q\n  nodash: %q",
			dashed, nodash, wDashed, wNodash)
	}
}
